LISTA = [['add', ['adicionar'], 'added', 'added'],       ['arise', ['erguer', 'levantar'], 'arose', 'arisen'],
        ['awake', ['acordar', 'despertar'], 'awoke', 'awoken'], ['answer', ['responder'], 'answered', 'answered'],
        ['ask', ['perguntar'], 'asked', 'asked'],       ['be', ['ser', 'estar'], 'was-were', 'been'],
        ['bear', ['suportar', 'aguentar'], 'bore', 'borne'],    ['beat', ['bater', 'espancar', 'superar', 'vibrar', 'palpitar'], 'beat', 'beaten'],
        ['become', ['tornar-se'], 'became', 'become'],  ['begin', ['comecar', 'iniciar'], 'began', 'begun'],
        ['bend', ['curvar', 'entortar'], 'bent', 'bent'],       ['bet', ['apostar'], 'bet', 'bet'],
        ['bite', ['morder', 'engolir-a-isca'], 'bit', 'bitten'],        ['bring', ['trazer', 'servir'], 'brought', 'brought'],
        ['bleed', ['sangrar'], 'bled', 'bled'], ['blow', ['soprar', 'assobiar'], 'blew', 'blown'],
        ['break', ['quebrar', 'romper'], 'broke', 'broken'],    ['build', ['construir', 'fabricar'], 'built', 'built'],
        ['burn', ['queimar', 'incendiar'], 'burnt', 'burnt'],   ['buy', ['comprar'], 'bought', 'bought'],
        ['call', ['chamar', 'ligar'], 'called', 'called'],      ['can', ['poder'], 'could', ''],
        ['cast', ['arremessar', 'jogar'], 'cast', 'cast'],      ['carry', ['carregar'], 'carried', 'carried'],
        ['catch', ['pegar', 'adquirir'], 'caught', 'caught'],   ['change', ['mudar'], 'changed', 'changed'],
        ['choose', ['escolher', 'selecionar'], 'chose', 'chosen'],      ['close', ['fechar'], 'closed', 'closed'],
        
        #

        ['come', ['vir'], 'came', 'come'],      ['cost', ['custar'], 'cost', 'cost'],
        ['cover', ['cobrir'], 'covered', 'covered'],    ['cry', ['chorar'], 'cried', 'cried'],
        ['cut', ['cortar'], 'cut', 'cut'],      ['deal', ['negociar', 'distribuir'], 'dealt', 'dealt'],
        ['dig', ['cavar', 'escavar'], 'dug', 'dug'],    ['do', ['fazer'], 'did', 'done'],
        ['draw', ['desenhar', 'extrair'], 'drew', 'drawn'],     ['drink', ['beber'], 'drank', 'drunk'],
        ['drive', ['dirigir'], 'drove', 'driven'],    ['dry', ['secar'], 'dried', 'dried'],
        ['eat', ['comer'], 'ate', 'eaten'],     ['end', ['acabar'], 'ended', 'ended'],
        ['explain', ['explicar'], 'explained', 'explained'],    ['fall', ['cair', 'diminuir', 'decrescer'], 'fell', 'fallen'],
        ['feel', ['sentir', 'notar'], 'felt', 'felt'],  ['fight', ['lutar', 'brigar'], 'fought', 'fought'],
        ['fill', ['encher', 'preencher'], 'filled', 'filled'],       ['find', ['encontrar', 'achar'], 'found', 'found'],
        ['fly', ['voar'], 'flew', 'flown'],     ['follow', ['seguir'], 'followed', 'followed'],
        ['forbid', ['proibir'], 'forbade', 'forbidden'],        ['forget', ['esquecer-se'], 'forgot', 'forgotten'],
        ['forgive', ['perdoar'], 'forgave', 'forgiven'],        ['forsake', ['abandonar', 'deserdar'], 'forsook', 'forsaken'],
        ['freeze', ['congelar'], 'froze', 'frozen'],    ['get', ['conseguir', 'obter', 'pegar'], 'got', 'got'],
        ['give', ['dar'], 'gave', 'given'],     ['go', ['ir'], 'went', 'gone'],
        ['feed', ['alimentar', 'nutrir'], 'fed', 'fed'],
        
        #

        ['grow', ['crescer', 'florescer'], 'grew', 'grown'],
        ['hang', ['pendurar', 'suspender'], 'hung', 'hung'],	['happen', ['acontecer'], 'happened', 'happened'],
        ['have', ['ter'], 'had', 'had'],	['hear', ['ouvir', 'escutar'], 'heard', 'heard'],
        ['help', ['ajudar'], 'helped', 'helped'],	['hide', ['esconder-se', 'ocultar'], 'hid', 'hidden'],
        ['hit', ['bater', 'chocar-se'], 'hit', 'hit'],	['hold', ['segurar', 'agarrar'], 'held', 'held'],
        ['hurt', ['machucar'], 'hurt', 'hurt'],	['keep', ['manter', 'preservar'], 'kept', 'kept'],
        ['kneel', ['ajoelhar-se'], 'knelt', 'knelt'],	['knit', ['tricotar'], 'knit', 'knit'],
        ['know', ['saber', 'conhecer'], 'knew', 'known'],	['lay', ['por', 'colocar', 'deitar'], 'laid', 'laid'],
        ['lead', ['conduzir', 'liderar'], 'led', 'led'],	['leap', ['saltar', 'pular'], 'leapt', 'leapt'],
        ['learn', ['aprender'], 'learnt', 'learnt'],	['leave', ['deixar', 'partir'], 'left', 'left'],
        ['lend', ['emprestar'], 'lent', 'lent'],	['let', ['deixar', 'permitir'], 'let', 'let'],
        ['lie', ['deitar'], 'lay', 'lain'],	['light', ['acender', 'iluminar'], 'lit', 'lit'],
        ['like', ['gostar'], 'liked', 'liked'],	['listen', ['escutar'], 'listened', 'listened'],
        ['live', ['viver'], 'lived', 'lived'],	['look', ['olhar'], 'looked', 'looked'],
        ['lose', ['perder'], 'lost', 'lost'],	['love', ['amar'], 'loved', 'loved'],
        ['make', ['fazer', 'produzir'], 'made', 'made'],
        
        #
        
        ['may', ['poder'], 'might', ''],
        ['mean', ['significar'], 'meant', 'meant'],	['meet', ['encontrar', 'reunir'], 'met', 'met'],
        ['move', ['mover'], 'moved', 'moved'],	['need', ['precisar'], 'needed', 'needed'],
        ['open', ['abrir'], 'opened', 'opened'],	['pay', ['pagar'], 'paid', 'paid'],
        ['plan', ['planejar'], 'planned', 'planned'],	['play', ['jogar', 'tocar', 'brincar'], 'played', 'played'],
        ['pull', ['puxar'], 'pulled', 'pulled'],	['put', ['colocar'], 'put', 'put'],
        ['quit', ['desistir', 'abandonar'], 'quit', 'quit'],	['read', ['ler'], 'read', 'read'],
        ['remember', ['lembrar'], 'remembered', 'remembered'],	['ride', ['cavalgar', 'andar-de-bike', 'andar-de-carro'], 'rode', 'ridden'],
        ['ring', ['soar', 'tocar-campainha'], 'rang', 'rung'],	['rise', ['erguer-se', 'levantar-se'], 'rose', 'risen'],
        ['run', ['correr'], 'ran', 'run'],	['saw', ['serrar'], 'sawed', 'sawn'],
        ['say', ['dizer'], 'said', 'said'],	['see', ['ver'], 'saw', 'seen'],
        ['seem', ['parecer'], 'seemed', 'seemed'],	['seek', ['procurar', 'pedir', 'almejar'], 'sought', 'sought'],
        ['sell', ['vender'], 'sold', 'sold'],	['set', ['por', 'ajustar'], 'set', 'set'],
        ['sew', ['costurar'], 'sewed', 'sewn'],	['shake', ['sacudir', 'agitar', 'apertar-a-mao'], 'shook', 'shaken'],
        ['shave', ['barbear'], 'shaved', 'shaved'],	['shine', ['brilhar'], 'shone', 'shone'],
        ['shoot', ['atirar', 'ferir-com-tiro'], 'shot', 'shot'],
        
        #
        
        ['show', ['mostrar', 'atirar'], 'showed', 'show'],
        ['shred', ['picar', 'retalhar', 'rasgar', 'cortar-em-pedacos'], 'shred', 'shred'],	['shrink', ['contrair', 'encolher'], 'shrank', 'shrunk'],
        ['shut', ['tampar', 'cerrar', 'fechar'], 'shut', 'shut'],	['sing', ['cantar'], 'sang', 'sung'],
        ['sink', ['afundar'], 'sank', 'sunk'],	['sit', ['sentar-se'], 'sat', 'sat'],
        ['slay', ['matar', 'assassinar', 'arruinar', 'destruir'], 'slew', 'slain'],	['sleep', ['dormir'], 'slept', 'slept'],
        ['slide', ['deslizar', 'escorregar'], 'slid', 'slid'],	['smell', ['cheirar'], 'smelt', 'smelt'],
        ['sow', ['semear'], 'sowed', 'sown'],	['speak', ['falar', '(mododefalar)'], 'spoke', 'spoken'],
        ['spell', ['soletrar'], 'spelt', 'spelt'],	['spend', ['gastar-dinheiro', 'gastar-tempo'], 'spent', 'spent'],
        ['spill', ['derramar'], 'spilt', 'spilt'],	['spin', ['girar'], 'spun', 'spun'],
        ['spoil', ['estragar', 'destruir', 'mimar'], 'spoilt', 'spoilt'],	['spread', ['espalhar', 'estender'], 'spread', 'spread'],
        ['spring', ['saltar', 'lancar-se'], 'sprang', 'sprung'],	['stand', ['por-se-de-pe'], 'stood', 'stood'],
        ['start', ['comecar'], 'started', 'started'],	['stay', ['ficar'], 'stayed', 'stayed'],
        ['steal', ['roubar'], 'stole', 'stolen'],	['stick', ['fincar', 'cravar'], 'stuck', 'stuck'],
        ['sting', ['picar', 'ferroar'], 'stung', 'stung'],	['stink', ['enjoar', 'feder'], 'stank', 'stunk'],
        ['stop', ['parar'], 'stopped', 'stopped'],	['strick', ['bater', 'golpear'], 'struck', 'struck'],]


def get():
    return LISTA
